language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install numpy
script:
    - binsearch_test.py
after_success:
    - coveralls